// <auto-generated />
using System;
using EasyBank.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyBank.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230908045308_AddedCustomerAndCardAndHistory2")]
    partial class AddedCustomerAndCardAndHistory2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyBank.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb2afd88-3842-4388-9591-aebc9accb16a"),
                            CardNumber = "4482340272687",
                            CustomerId = new Guid("53e7819d-dea0-4c6f-bdbd-a0d353bf183e"),
                            IsBlocked = false,
                            PinCode = "745"
                        },
                        new
                        {
                            Id = new Guid("45edb750-2524-416b-823d-b4ae7152a6bf"),
                            CardNumber = "6771334287919796",
                            CustomerId = new Guid("53258aa7-a780-4965-af01-ecb607115c55"),
                            IsBlocked = false,
                            PinCode = "883"
                        },
                        new
                        {
                            Id = new Guid("c5f7f118-4502-48f9-99d5-fc6f5758b0be"),
                            CardNumber = "5487-1570-1238-3203",
                            CustomerId = new Guid("941280e4-6df9-4eec-813b-17ba3be24f1c"),
                            IsBlocked = false,
                            PinCode = "911"
                        },
                        new
                        {
                            Id = new Guid("41a6d02f-0cae-4815-b6db-8b269b5d6e70"),
                            CardNumber = "3582-5504-7492-2196",
                            CustomerId = new Guid("6590cc33-58b2-4a48-8f23-ed61ea2354c0"),
                            IsBlocked = false,
                            PinCode = "309"
                        },
                        new
                        {
                            Id = new Guid("2526240e-db5f-4447-87b4-79c701ab40fd"),
                            CardNumber = "5018025875456406621",
                            CustomerId = new Guid("290f4fc2-46ef-45c5-9872-5b3e7eebef36"),
                            IsBlocked = false,
                            PinCode = "078"
                        },
                        new
                        {
                            Id = new Guid("de70dd27-30b2-4abe-ae56-8ae76d1da0da"),
                            CardNumber = "6759-8701-8313-6122",
                            CustomerId = new Guid("f2321e0c-63a4-498a-ac16-1849d32bc30e"),
                            IsBlocked = false,
                            PinCode = "535"
                        },
                        new
                        {
                            Id = new Guid("a29be2bc-fb84-46ce-aed0-547b82bb882d"),
                            CardNumber = "5566-4237-4209-9251",
                            CustomerId = new Guid("f67ca135-209e-47d5-9d83-9f4983be4b45"),
                            IsBlocked = false,
                            PinCode = "803"
                        },
                        new
                        {
                            Id = new Guid("5c19aa4f-4253-4735-83e5-a469a3f09a62"),
                            CardNumber = "6759-9068-5309-3480-83",
                            CustomerId = new Guid("70e3d08d-4fa8-471e-878a-61856a059745"),
                            IsBlocked = false,
                            PinCode = "677"
                        },
                        new
                        {
                            Id = new Guid("e9ab7ccb-1678-43aa-ac7a-2833c19de3f8"),
                            CardNumber = "6443-6264-2114-6593-7756",
                            CustomerId = new Guid("fb9f4482-a04f-4b2d-aed0-24ef3c9a0023"),
                            IsBlocked = false,
                            PinCode = "643"
                        },
                        new
                        {
                            Id = new Guid("c68cb9a0-e0c2-4d61-9cb1-56b32fb63eff"),
                            CardNumber = "6767-2418-9751-2794",
                            CustomerId = new Guid("4012a619-b02d-476b-ab44-7f6558268a06"),
                            IsBlocked = false,
                            PinCode = "568"
                        });
                });

            modelBuilder.Entity("EasyBank.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53e7819d-dea0-4c6f-bdbd-a0d353bf183e"),
                            Address = "(896) 738-0326 x2834",
                            FullName = "Shelly Ullrich"
                        },
                        new
                        {
                            Id = new Guid("53258aa7-a780-4965-af01-ecb607115c55"),
                            Address = "(744) 485-1093",
                            FullName = "James Wisoky"
                        },
                        new
                        {
                            Id = new Guid("941280e4-6df9-4eec-813b-17ba3be24f1c"),
                            Address = "(658) 874-1180 x3992",
                            FullName = "Flora O'Kon"
                        },
                        new
                        {
                            Id = new Guid("6590cc33-58b2-4a48-8f23-ed61ea2354c0"),
                            Address = "549.886.8462",
                            FullName = "Lola Buckridge"
                        },
                        new
                        {
                            Id = new Guid("290f4fc2-46ef-45c5-9872-5b3e7eebef36"),
                            Address = "(463) 875-0780",
                            FullName = "Wilma Jerde"
                        },
                        new
                        {
                            Id = new Guid("f2321e0c-63a4-498a-ac16-1849d32bc30e"),
                            Address = "836.646.9283 x214",
                            FullName = "Annie Beier"
                        },
                        new
                        {
                            Id = new Guid("f67ca135-209e-47d5-9d83-9f4983be4b45"),
                            Address = "(912) 809-4063 x9668",
                            FullName = "Cecil Conroy"
                        },
                        new
                        {
                            Id = new Guid("70e3d08d-4fa8-471e-878a-61856a059745"),
                            Address = "(972) 635-8421 x6829",
                            FullName = "Victor Heidenreich"
                        },
                        new
                        {
                            Id = new Guid("fb9f4482-a04f-4b2d-aed0-24ef3c9a0023"),
                            Address = "834-988-5210",
                            FullName = "Marcia Hartmann"
                        },
                        new
                        {
                            Id = new Guid("4012a619-b02d-476b-ab44-7f6558268a06"),
                            Address = "(720) 713-1574",
                            FullName = "Rosemarie Mills"
                        });
                });

            modelBuilder.Entity("EasyBank.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da607a84-4cb1-4ec1-9897-75c5f16dfaa4"),
                            Email = "otabek.pro@hotmail.com",
                            FullName = "Otabek Rustamov",
                            Password = "123123123",
                            Phone = "1-394-290-2119 x9165",
                            Position = "Developer",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b25b7481-536b-4934-bc84-86e3dc71a335"),
                            Email = "Ramiro.Rolfson39@gmail.com",
                            FullName = "Ramiro Rolfson",
                            Password = "123123123",
                            Phone = "299.756.9869",
                            Position = "cook",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("1cfc9281-c63f-4901-890c-2ef1a0cd4316"),
                            Email = "Hugh35@gmail.com",
                            FullName = "Hugh Bernier",
                            Password = "123123123",
                            Phone = "759.500.0512",
                            Position = "cook",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = new Guid("91378948-4058-4d1c-9d11-016f23261fb5"),
                            Email = "Shelly.Wintheiser@hotmail.com",
                            FullName = "Shelly Wintheiser",
                            Password = "123123123",
                            Phone = "398-372-4933 x38264",
                            Position = "cook",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = new Guid("f460a4e3-527d-4d64-8164-c80556f16a1f"),
                            Email = "Lucia7@hotmail.com",
                            FullName = "Lucia Mann",
                            Password = "123123123",
                            Phone = "676-445-3765",
                            Position = "hr",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = new Guid("b5b2c2c9-fa69-496d-b896-49a0c1ead991"),
                            Email = "Ramon.Parisian@gmail.com",
                            FullName = "Ramon Parisian",
                            Password = "123123123",
                            Phone = "(273) 628-1907",
                            Position = "developer",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("EasyBank.Models.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CustomerId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("EasyBank.Models.Card", b =>
                {
                    b.HasOne("EasyBank.Models.Customer", "Customer")
                        .WithMany("Cards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EasyBank.Models.History", b =>
                {
                    b.HasOne("EasyBank.Models.Card", "Card")
                        .WithMany("CardHistory")
                        .HasForeignKey("CardId");

                    b.HasOne("EasyBank.Models.Customer", "Customer")
                        .WithMany("CustomerHistory")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Card");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EasyBank.Models.Card", b =>
                {
                    b.Navigation("CardHistory");
                });

            modelBuilder.Entity("EasyBank.Models.Customer", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("CustomerHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
