// <auto-generated />
using System;
using EasyBank.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyBank.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230908122940_UpdateHistoryModel")]
    partial class UpdateHistoryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyBank.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f32f632c-1128-41b0-b338-31338ba38fe1"),
                            CardNumber = "6759-8755-3163-7218",
                            CustomerId = new Guid("9f31d285-1d74-44eb-b9a6-d145a14b2a03"),
                            IsBlocked = false,
                            PinCode = "965"
                        },
                        new
                        {
                            Id = new Guid("21a985f4-021b-4e9f-91f0-83651a27d442"),
                            CardNumber = "503866258335256731",
                            CustomerId = new Guid("acbe706c-c287-49ea-9f37-2c58c7d1b9d2"),
                            IsBlocked = false,
                            PinCode = "671"
                        },
                        new
                        {
                            Id = new Guid("483c85e7-bdf6-4bf3-8481-901a349dedf9"),
                            CardNumber = "5482-9497-8583-4130",
                            CustomerId = new Guid("2b01c0c7-b673-4bfb-9e01-f391fca96648"),
                            IsBlocked = false,
                            PinCode = "520"
                        },
                        new
                        {
                            Id = new Guid("4cc78216-70d0-4ea6-9c60-49e2baa9f7ea"),
                            CardNumber = "5515-4139-8377-4946",
                            CustomerId = new Guid("67ec6f99-2efe-4dfd-bc5c-ead352d1fada"),
                            IsBlocked = false,
                            PinCode = "754"
                        },
                        new
                        {
                            Id = new Guid("d9f9cb11-3121-4c60-95c3-190028b81d2d"),
                            CardNumber = "3696-043122-5815",
                            CustomerId = new Guid("748b2e6b-55dd-4ec7-9200-f113620bf300"),
                            IsBlocked = false,
                            PinCode = "851"
                        },
                        new
                        {
                            Id = new Guid("992c45b1-5b2d-4134-9586-6b6a6a80caf4"),
                            CardNumber = "3019-625126-2440",
                            CustomerId = new Guid("9ce0a659-6edf-4202-a752-e388927b19d6"),
                            IsBlocked = false,
                            PinCode = "414"
                        },
                        new
                        {
                            Id = new Guid("2654aefe-4fd1-48c1-a171-a6ca5eb16f54"),
                            CardNumber = "675997444034189054",
                            CustomerId = new Guid("f90a0da2-8aa6-4ef3-ab02-63e37b2b3337"),
                            IsBlocked = false,
                            PinCode = "798"
                        },
                        new
                        {
                            Id = new Guid("2f231e3b-e366-4ee0-a6d1-3d545aabcb59"),
                            CardNumber = "6011-5504-4149-3192",
                            CustomerId = new Guid("1a06f47d-a66a-4614-93d5-a1f15360e366"),
                            IsBlocked = false,
                            PinCode = "801"
                        },
                        new
                        {
                            Id = new Guid("c7549542-4afb-40e2-9304-35883955c2c9"),
                            CardNumber = "6397-3974-1578-5391",
                            CustomerId = new Guid("86e1e7da-5b87-4191-9b1f-1b6c549dc913"),
                            IsBlocked = false,
                            PinCode = "120"
                        },
                        new
                        {
                            Id = new Guid("a3b4b1a9-03b9-4259-bf69-8c3ea72b975c"),
                            CardNumber = "3765-416645-94883",
                            CustomerId = new Guid("f34498d8-e3f6-479e-a16c-4e46ee26646e"),
                            IsBlocked = false,
                            PinCode = "881"
                        });
                });

            modelBuilder.Entity("EasyBank.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f31d285-1d74-44eb-b9a6-d145a14b2a03"),
                            Address = "403.298.0806",
                            FullName = "Alfonso Smitham"
                        },
                        new
                        {
                            Id = new Guid("acbe706c-c287-49ea-9f37-2c58c7d1b9d2"),
                            Address = "1-549-359-8629 x702",
                            FullName = "Rene Parisian"
                        },
                        new
                        {
                            Id = new Guid("2b01c0c7-b673-4bfb-9e01-f391fca96648"),
                            Address = "826-820-9725 x7890",
                            FullName = "Tony Larkin"
                        },
                        new
                        {
                            Id = new Guid("67ec6f99-2efe-4dfd-bc5c-ead352d1fada"),
                            Address = "1-566-897-1962 x109",
                            FullName = "Jan DuBuque"
                        },
                        new
                        {
                            Id = new Guid("748b2e6b-55dd-4ec7-9200-f113620bf300"),
                            Address = "864-557-6290",
                            FullName = "Eduardo Feeney"
                        },
                        new
                        {
                            Id = new Guid("9ce0a659-6edf-4202-a752-e388927b19d6"),
                            Address = "1-647-289-2494 x700",
                            FullName = "Viola Schamberger"
                        },
                        new
                        {
                            Id = new Guid("f90a0da2-8aa6-4ef3-ab02-63e37b2b3337"),
                            Address = "1-674-299-1280",
                            FullName = "Bobbie Hintz"
                        },
                        new
                        {
                            Id = new Guid("1a06f47d-a66a-4614-93d5-a1f15360e366"),
                            Address = "1-571-758-8170 x9707",
                            FullName = "Billie Windler"
                        },
                        new
                        {
                            Id = new Guid("86e1e7da-5b87-4191-9b1f-1b6c549dc913"),
                            Address = "(221) 366-8280 x195",
                            FullName = "Sheldon Barrows"
                        },
                        new
                        {
                            Id = new Guid("f34498d8-e3f6-479e-a16c-4e46ee26646e"),
                            Address = "1-787-587-8137",
                            FullName = "Viola Greenfelder"
                        });
                });

            modelBuilder.Entity("EasyBank.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45c43049-e4ef-4455-904c-99f46fec4da4"),
                            Email = "otabek.pro@hotmail.com",
                            FullName = "Otabek Rustamov",
                            Password = "123123123",
                            Phone = "349-665-2458 x9800",
                            Position = "Developer",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("28f8689d-f2db-4ad7-bf0d-a6b495e62a36"),
                            Email = "Terry.Kutch90@yahoo.com",
                            FullName = "Terry Kutch",
                            Password = "123123123",
                            Phone = "(404) 795-0653",
                            Position = "developer",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("ad1b5262-99f2-41fc-9918-3ca419b42aa0"),
                            Email = "Sara_Klocko@gmail.com",
                            FullName = "Sara Klocko",
                            Password = "123123123",
                            Phone = "(619) 704-7138 x02077",
                            Position = "cook",
                            Role = "Director"
                        },
                        new
                        {
                            Id = new Guid("02ee667d-b2c1-484f-969d-7dcdc3220fc1"),
                            Email = "Francis41@gmail.com",
                            FullName = "Francis Cremin",
                            Password = "123123123",
                            Phone = "1-719-370-1506 x487",
                            Position = "cook",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("be6de4f0-1d4f-43c8-8dc2-3a17b9612665"),
                            Email = "Isaac.Schuppe33@gmail.com",
                            FullName = "Isaac Schuppe",
                            Password = "123123123",
                            Phone = "323-484-7583 x8995",
                            Position = "developer",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = new Guid("844a9041-0f22-466a-a355-0199463f8104"),
                            Email = "Rudy20@hotmail.com",
                            FullName = "Rudy Smitham",
                            Password = "123123123",
                            Phone = "(816) 724-1699",
                            Position = "security",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("EasyBank.Models.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("EasyBank.Models.Card", b =>
                {
                    b.HasOne("EasyBank.Models.Customer", "Customer")
                        .WithMany("Cards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EasyBank.Models.History", b =>
                {
                    b.HasOne("EasyBank.Models.Card", null)
                        .WithMany("CardHistory")
                        .HasForeignKey("CardId");

                    b.HasOne("EasyBank.Models.Customer", null)
                        .WithMany("CustomerHistory")
                        .HasForeignKey("CustomerId");

                    b.HasOne("EasyBank.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EasyBank.Models.Card", b =>
                {
                    b.Navigation("CardHistory");
                });

            modelBuilder.Entity("EasyBank.Models.Customer", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("CustomerHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
